### ISSUE TITLE
Add 0xBitcoin as a base-value token

### ISSUE THREAD

**Issue by icinsight** [0xTracker/0x-tracker-worker#220]
There is an increasing volume with 0xBitcoin base pair. 0xchange.org is a "reference implementation" (or poster-child implementation...) of the Launch Kit and that volume will be missed in statistics because 0x Tracker dismisses the $USD value of these pairs.

Website: https://0xbitcoin.org/
Contract: 0xb6ed7644c69416d67b522e20bc294a9a9b405b31
0x Tracker: https://0xtracker.com/tokens/0xb6ed7644c69416d67b522e20bc294a9a9b405b31

**Comment by icinsight** [comment]
If the tracker supports only mainstream ones it is a strong statement against innovation and smaller projects that "have no value"... I think that is perfectly against 0x Project's values and goals. Now, as you are getting some traction and new innovative projects are joining the 0x movement everything in the 0x ecosystem should be aligned with these goals.

**Comment by cbovis** [comment]
@icinsight apologies for the late response on this. I've been doing a lot of traveling recently so a lot of my messages regarding 0x Tracker have been slipping to the side.

Token prices for base pairs are currently pulled in from the Cryptocompare API and have been limited to a select number of tokens due to a couple of reasons:

1) Tokens with non-USD pairings on exchanges monitored by Cryptocompare can often report large deviations from the norm in their price due to some issues in the Cryptocompare API. This has caused issues on 0x Tracker in the past, with volumes being reported way above where they should actually be.
2) 0x Tracker currently uses the free API tier of Cryptocompare which imposes low limits on the number of API requests that can be made. Each base token added to 0x Tracker pushes closer to our accounts limits.

Issue #2 shouldn't be a problem in this case since volume is currently low (and if it become higher we'd want to ensure it's recorded). Issue #1 would be a problem though because 0xBitcoin is not paired with USD on cryptocompare (https://www.cryptocompare.com/coins/0xbtc/overview). 

Potentially prices could be pulled for BTC from Cryptocompare, which has a reliable USD pair. I'm not fully up to speed on how well 0XBTC has been tracking BTC though, so this may or may not be a good plan of attack. Let me do some research and I'll get back to you soon 🙌

**Comment by icinsight** [comment]
Thanks for you response @cbovis.

I'm familiar with Cryptocompare, and their data on 0xBTC is almost worthless as it is today. Their API converts any pair into USD, if you specify that in your query string, though. (Their website interface to data does not do that, so that is a bit confusing.) It doesn't change the fact that they don't observe any significant markets for 0xBTC. Getting data directly form markets is the only option for 0xBTC proce information, because the value is not pegged to any other asset.

My solution (not even workaround) is to use CoinGecko - their data is also free and much better for 0xBTC. Another solution (long term) is to ask 0x project to cover the subscription - don't you think?

Just FYI, I approached Cryptocompare yesterday with a message (below). Let's see if that changes anything.

![image](https://user-images.githubusercontent.com/39129866/60756815-add9df80-9fd8-11e9-8504-d01d8e22f497.png)

**Comment by cbovis** [comment]
@icinsight thanks for the write up. 

Since 0xBitcoin isn't pegged to BTC, and has no USD tracking on Cryptocompare it's not going to be feasible to support as a base token at this point in time. Given the low volume of fills involving 0xBitcoin, the cost/benefit ratio of a CoinGecko integration is low.

From what I can see the CoinGecko API only provides historical pricing at daily accuracy which would rule it out as an alternative to Cryptocompare. One of the benefits of Cryptocompare is that their API provides minute accuracy for prices in the last week, and hourly accuracy for prices further in the past. This is important for failure recovery (e.g. 0x Tracker worker going down for a few hours), and back filling of data (e.g. a new base token being supported).

**Comment by icinsight** [comment]
Understood, thanks for looking into this!
